artifacts:
  kpro_release_SchmeeckleBatStudy_20260209_174126:
    name: kpro_release_SchmeeckleBatStudy_20260209_174126
    type: release_bundle
    workflow: release
    file_path: C:/Users/Triad/OneDrive/Documents/R Projects/Kpro_Masterfile_Pipeline/results/releases/kpro_release_SchmeeckleBatStudy_20260209_174126.zip
    file_hash_sha256: 2485501448c870a9a332c05ed00b26dabd9d1b9008058e2f314de741e1e39a2a
    file_size_bytes: 5068056.0
    created_utc: '2026-02-09T23:41:31Z'
    pipeline_version: '2.1'
    input_artifacts:
    - kpro_master
    - cpn_final
    metadata:
      study_id: SchmeeckleBatStudy
      n_files: 35
      zip_size_bytes: 5068056.0
last_modified_utc: '2026-02-09T23:41:31Z'
